name: Validate iOS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'package/ios/**'
  pull_request:
    paths:
      - '.github/workflows/validate-ios.yml'
      - 'package/ios/**'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v4
      - name: Run SwiftLint GitHub Action (--strict)
        uses: norio-nomura/action-swiftlint@master
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: ios